MotChallenge2DBox
MOT20-Test
Traceback (most recent call last):
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\datasets\mot_challenge_2d_box.py", line 325, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\datasets\_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT20-01, frame: 248, ids: -1)





MotChallenge2DBox
MOT20-Test
Traceback (most recent call last):
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\datasets\mot_challenge_2d_box.py", line 325, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\datasets\_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT20-01, frame: 248, ids: -1)





MotChallenge2DBox
MOT20-Test
Traceback (most recent call last):
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\eval.py", line 113, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\eval.py", line 222, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\_timing.py", line 17, in wrap
    result = f(*args, **kw)
             ^^^^^^^^^^^^^^
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\datasets\mot_challenge_2d_box.py", line 325, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "C:\CacMonHoc\KLTN\test_model\TrackEval\trackeval\datasets\_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT20-01, frame: 248, ids: -1)





